services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword
    ports:
      - "27017:27017"

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    ports:
      - "9000:9000"
    volumes:
      - ./minio/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/bin/sh", "/entrypoint.sh"]

  app:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      APP_PORT: 80

      S3_ENDPOINT: http://minio:9000
      S3_REGION: us-east-1
      S3_ACCESS_KEY_ID: miniouser
      S3_SECRET_ACCESS_KEY: miniopassword

      S3_BUCKET_MEASURE_UPLOAD: measure-upload

      MONGO_URI: mongodb://mongouser:mongopassword@mongo:27017/measure-app?authSource=admin

      PUBLIC_DOWNLOAD_ENDPOINT: http://localhost:3000/download
    depends_on:
      - mongo
      - minio